fix: fix ui button
Adslot/adslot-ui pull request #1085
Opened 2020-10-09 01:16 UTC by glenkurniawan-adslot

## Description

After testing with local on grid and direct web, I found that the button that we have on both of them has additional `btn` className.. therefore, I just revert back the style changes on aui--button and add `btn` as the baseClass

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Manual testing step?

## Screenshots (if appropriate):

2020-10-11 10:12 UTC, Harris-YWang approved these changes
LGTM

2020-10-12 22:21 UTC, superpower1 commented on src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap
> +          <div>
Wondering why there is a div wrapper here?

2020-10-12 22:23 UTC, glenkurniawan-adslot commented on src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap
> +          <div>
@superpower1 because of this: 
```
<button
      data-testid="button-wrapper"
      disabled={isLoading || disabled}
      className={classes}
      {...expandDts(dts)}
      {..._.omit(props, _.keys(adslotButtonPropTypes))}
    >
      {renderSpinner()}
      **<div className={isLoading ? 'aui--button-children-container' : null}>{children}</div>**
    </button>
```

2020-10-12 22:46 UTC, superpower1 approved these changes

2020-10-15 21:03 UTC, Harris-YWang requested changes
Seems you've made some changes after my last review, and some stylings are broken again. please double check the style of each button per https://ui.adslot.com/button  Thanks mate.

Also, here is a console.error from the unit tests as follows, and it'd better to fix:
![Screen Shot 2020-10-16 at 7 55 01 am](https://user-images.githubusercontent.com/42738416/96185562-cd0a3f80-0f85-11eb-8228-01727a7d9aa4.png)

2020-10-15 22:03 UTC, glenkurniawan-adslot commented
> Seems you've made some changes after my last review, and some stylings are broken again. please double check the style of each button per https://ui.adslot.com/button Thanks mate.

@Harris-YWang Yeah, Haofu suggested to remove the `btn` className, instead of adding it (because btn is coming from bootstrap.. I will work on the fix.. thanks

2020-10-16 00:58 UTC, Harris-YWang approved these changes
Compared with the existing button design, everything looks good to me now. :+1:

2020-10-18 22:16 UTC, lightbringer1991 commented
seems like my PR is duplicated https://github.com/Adslot/adslot-ui/pull/1089
will close my PR and track this one instead

2020-10-18 22:17 UTC, lightbringer1991 commented on src/components/Button/index.jsx
>    const classes = classNames(baseClass, className, {
I think we need to put `className` at the end of the class chain so the custom styles can override previous classes if needed.

2020-10-18 22:18 UTC, lightbringer1991 commented on src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap
> +          class="aui--button btn-primary"
no need to add `aui--button` here, the component will generate it automatically

2020-10-18 22:19 UTC, glenkurniawan-adslot commented on src/components/Button/index.jsx
>    const classes = classNames(baseClass, className, {
ok.. sounds good... will update this

2020-10-18 22:20 UTC, lightbringer1991 commented on src/components/TreePicker/Node/index.jsx
> +                className="btn-inverse button-xs"
I think we should use `inverse` prop instead of declaring class here.
```
<Button inverse className="button-xs" {...props}>....</Button>
```

2020-10-18 22:21 UTC, glenkurniawan-adslot commented on src/components/TreePicker/Node/index.jsx
> +                className="btn-inverse button-xs"
they are basically doing the same thing.. so I think either is fine.. ex: we can use btn-large or bsSize="large"

2020-10-18 22:28 UTC, glenkurniawan-adslot commented on src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap
> +          class="aui--button btn-primary"
@lightbringer1991 ok.. will update this

2020-10-19 01:23 UTC, lightbringer1991 commented on src/components/Button/index.jsx
> +          ['btn-default', 'btn-inverse', 'btn-default btn-inverse', 'btn-inverse btn-default'].includes(className)),
I think `btn-default` no longer exists, it's now `aui--btn-default`, so we can simplify the conditions here a bit.

I guess it would be breaking for the following suggestions, just throwing it out here. We drop all checking conditions for class names, make the user responsible for what class they want to put in, and force them to use props where possible. E.g.
```
const classes = classNames(
  baseClass,
  {
    'btn-inverse': inverse,
    'aui--btn-default': !bsStyle,
    'btn-large': size === 'large',
    [`btn-${bsStyle}`]: !_.isEmpty(bsStyle),
  },
  className
);
```

2020-10-19 01:32 UTC, lightbringer1991 approved these changes
LGTM

2020-10-19 03:26 UTC, glenkurniawan-adslot commented on src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap
> +          class="aui--button btn-primary"
@lightbringer1991 as mentioned, this is needed because the snapshot breaks the <Button> to <button><div></div></button>

2020-10-19 22:50 UTC, lteacher approved these changes

2020-10-20 05:32 UTC, merged